inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  EnabledByDefault: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/bundle/**/*'
    - '**/*\.spec'

################################################################################
#
# Rules that depart from rubocop defaults
#
################################################################################

# we may not need this after finishing RSpec conversion
# seems like `rubocop-rspec` already excludes the `spec/` directory
Style/MethodCalledOnDoEndBlock: { Exclude: [test/**/*.rb, spec/**/*.rb] }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: consistent_comma }
