module Magick
  class OptionalMethodArguments
    attr_writer highlight_color: magick_color
    attr_writer lowlight_color: magick_color

    def initialize: (magick_image img) -> void
    def define: (string key, ?string? value) -> String
    def method_missing: (untyped mth, untyped val) ?{ (*untyped, **untyped) -> untyped } -> untyped
  end
end
